"""DEX Protocols Package"""

from .dodo import DODO_FUNCTIONS
from .bancor import BANCOR_FUNCTIONS
from .platypus import PLATYPUS_FUNCTIONS
from .solidly import SOLIDLY_FUNCTIONS
from .gmx import GMX_FUNCTIONS
from .hashflow import HASHFLOW_FUNCTIONS
from .maverick import MAVERICK_FUNCTIONS
from .gnosis import GNOSIS_FUNCTIONS
from .velodrome import VELODROME_FUNCTIONS
from .camelot import CAMELOT_FUNCTIONS
from .traderjoe import TRADERJOE_FUNCTIONS
from .beethoven import BEETHOVEN_FUNCTIONS
from .balancer_v2 import BALANCER_V2_FUNCTIONS
from .wombat import WOMBAT_FUNCTIONS

DEX_PROTOCOLS = {
    'DODO': DODO_FUNCTIONS,
    'BANCOR': BANCOR_FUNCTIONS,
    'PLATYPUS': PLATYPUS_FUNCTIONS,
    'SOLIDLY': SOLIDLY_FUNCTIONS,
    'GMX': GMX_FUNCTIONS,
    'HASHFLOW': HASHFLOW_FUNCTIONS,
    'MAVERICK': MAVERICK_FUNCTIONS,
    'GNOSIS': GNOSIS_FUNCTIONS,
    'VELODROME': VELODROME_FUNCTIONS,
    'CAMELOT': CAMELOT_FUNCTIONS,
    'TRADERJOE': TRADERJOE_FUNCTIONS,
    'BEETHOVEN': BEETHOVEN_FUNCTIONS,
    'BALANCER_V2': BALANCER_V2_FUNCTIONS,
    'WOMBAT': WOMBAT_FUNCTIONS
}